### ISSUE TITLE
Stopped working after macOS Catalina Upgrade

### ISSUE THREAD

**Issue by snadowitz** [pravdomil/Native-Trackpad#5]
MacOs will no longer even allow an install of the app. On running Fusion360 the app throws an exception that says it can no longer run for the same reason.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/57176889/67851576-b2a53f00-fb45-11e9-9029-b171e0a24e39.png">

**Comment by pravdomil** [comment]
related to https://github.com/pravdomil/Fix-Sketch-Trackpad-Speed/issues/5

**Comment by pravdomil** [comment]
there is no plan to support macOS Catalina, sorry

**Comment by snadowitz** [comment]
Fair enough.

**Comment by rrooding** [comment]
It seems to work when you Cmd-Click the pkg and select Open, bypassing the macOS developer check.

<img width="709" alt="Screenshot 2019-11-04 at 20 21 56" src="https://user-images.githubusercontent.com/6006/68150977-20d07400-ff41-11e9-9f92-6913fca7f01e.png">

**Comment by mrubioroy** [comment]
macOS 10.15 Catalina quarantines the library. You can whitelist it:
- Open a Terminal
- You're probably in your home dir, otherwise use the `cd` command
- Use the following command to get the com.apple.quarantine attribute:
`xattr -p com.apple.quarantine Library/Application\ Support/Autodesk/Autodesk\ Fusion\ 360/API/Scripts/NativeTrackpad/NativeTrackpad.dylib`
- Copy the string you get. It should be something like "**0081**;5b767f91;Safari;FF7FD04A-71DA-4993-8EFA-4F8202EBA1C1" Replace the first 4 characters by **00c1** and use **YOUR** modified string on the following command.
`xattr -w com.apple.quarantine "00c1;5b767f91;Safari;FF7FD04A-71DA-4993-8EFA-4F8202EBA1C1" Library/Application\ Support/Autodesk/Autodesk\ Fusion\ 360/API/Scripts/NativeTrackpad/NativeTrackpad.dylib`
- Launch Fusion 360

**Comment by 101crazycoder101** [comment]
all those didn't work for 1.15.3 beta but it worked for me doing this
`sudo installer -pkg /Users/[your users name]/Downloads/NativeTrackpad.pkg -target /
`
note: i have homebrew installed, not sure it that allowed me to do it
heres a guide of how to install this [HomeBrew](https://brew.sh/)

**Comment by ambethia** [comment]
> there is no plan to support macOS Catalina, sorry.

Why, if the fix is a signing issue?

Edit: Nevermind I see your thoughts on the issue in the other repository.

**Comment by scooper4711** [comment]
Seems to work just fine in Catalina. Just ctrl-click and select "Open" from the pop-up.
I think that all that's needed is to take the existing code and sign it in order to avoid this issue. But this work-around is trivial.
Thanks for this plugin!!

**Comment by nebbles** [comment]
Can confirm `Right click > Open` works to run the installer (when Fusion is closed). Installs and then works without issue upon starting Fusion. (macOS Catalina 10.15.2)

Many thanks for a fantastic plugin.

Perhaps updating the plugin page on Autodesk to say it can work on Catalina (although no direct support provided) since some may be discouraged and not realise that it does work!

**Comment by ryantschaper** [comment]
There is a VERY simple solution to this issue:
Go to the Settings App -> Security and Privacy
There should be a notification there of the download that was blocked.  From there, you can click the button "open anyway"

**Comment by pravdomil** [comment]
should be fixed now https://github.com/mertrois/Native-Trackpad/releases
